### ISSUE TITLE
Bug while trying to use capybara

### ISSUE THREAD

**Issue by eduardofiorezi** [Helabs/pah#462]
I generate a new app and create a feature with:

```
rails generate rspec:feature dashboard
```

When a run rake spec, i receive:

```
`<top (required)>': undefined method `feature' for main:Object (NoMethodError)
```

I found this solution:

http://stackoverflow.com/questions/19715220/rspec-capybara-feature-method-undefined-when-guard-runs-specs-in-watched-files

To fix, we need to remove this line:

https://github.com/Helabs/pah/blob/master/lib/pah/files/spec/spec_helper.rb#L9

**Comment by maurogeorge** [comment]
@eduardofiorezi you can change your spec to something like:

```ruby
RSpec.feature do
   # features here
end
```

**Comment by eduardofiorezi** [comment]
It work's.. Why not the default?

feature "Checkups", :type => :feature do
  pending "add some scenarios (or delete) #{__FILE__}"
end

**Comment by marcioj** [comment]
@eduardofiorezi maybe the generator is outdated

**Comment by maurogeorge** [comment]
@eduardofiorezi on RSpec 3 the team work to remove lot of monkey patching, like the `#should`. But remove this without keep suport is bad, because lot of books and posts uses the RSpec 2 syntax. So most of the new features are as commented configs on the default spec_helper.

Since pah is made to build a new rails app, we can use the most advanced features like the `disable_monkey_patching!`.

We can see more about [monkey patching on RSpec here](http://rspec.info/blog/2014/05/notable-changes-in-rspec-3/).

As you can [see here](https://github.com/rspec/rspec-rails/blob/master/lib/generators/rspec/feature/templates/feature_spec.rb) the default rspec-rails is to generate without the monkey patching.

As @marcioj said, the generator was updated only on the 3.2.0 as you can see [here](https://github.com/rspec/rspec-rails/blob/master/Changelog.md#320-development).

@eduardofiorezi if it is ok to you, please close this issue.

**Comment by eduardofiorezi** [comment]
I understand, but it is very strange the generator does not work properly.
