### ISSUE TITLE
Heroku addon PgBackups is deprecated.

### ISSUE THREAD

**Issue by guiloyins** [Helabs/pah#471]
Heroku make pgbackups as a part of CLI.
We need to remove the script that add this addon to the project when the "deploy immediately" is set to true.

More info [here](https://devcenter.heroku.com/articles/pgbackups)

**Comment by marano** [comment]
I've noticed we are using ```pgbackups:auto-month``` for automatic monthly backup. The problem is I couldn't find how to setup monthly backup with the new command. Only daily backups are documented. See [https://devcenter.heroku.com/articles/heroku-postgres-backups#scheduling-backups](https://devcenter.heroku.com/articles/heroku-postgres-backups#scheduling-backups)

**Comment by eduardofiorezi** [comment]
Related to https://github.com/Helabs/jumpup-heroku/issues/72
