### ISSUE TITLE
Can I create my project without flutie, bourbon and its friends?

### ISSUE THREAD

**Issue by yogodoshi** [Helabs/pah#482]
I know that "pah" is an opinionated gem but everytime I use it I have to remove the the same gems and edit some files... 

You guys must like those gems, other guys may not like them (me, for example). So can we make them optional? Like the other options we have when the project is being created.

**Comment by maurogeorge** [comment]
I think it is more easy to you remove the gems you don't want, some people for example remove jbuilder and turbolinks from a fresh rails app.

When we redesigned the Pah, we want this more opinated and without lot of questions.

If we add questions like:

- do you want flutie gem?
- do you want turbolinks gem?

The list can be enourmeous, and if we ask only once: "What gems you want remove?(Use comma)" and you enter like: flutie, turbolinks. The problem is we need to handle typos and some especial gems, like rollbar that creates a initializes, run a rake task and other gems that insert yourself on some css files.

You can think that Pah is a rails base app, like the [suspenders](https://github.com/thoughtbot/suspenders). In this base will have things you like, and what you don't like you can simple remove.

**Comment by andreanastacio** [comment]
ping @yogodoshi

**Comment by yogodoshi** [comment]
Sorry, I've seen this answer only now. @ndrluis there is nothing I can do here, @maurogeorge said its opinionated and they chose to install all those gems.
