### ISSUE TITLE
Choose a gem and create setup for javascript unit test

### ISSUE THREAD

**Issue by thiagogabriel** [Helabs/pah#487]
It is important to write tests for javascript code and the first step is to define a convention for every project. 

I never used this gem, but jasmine does not depend on any framework like ember or angular.
https://github.com/searls/jasmine-rails

It is also important to have the tests running on rake task for jumpup tasks.

**Comment by lunks** [comment]
If going with jasmine, I highly recommend teaspoon: https://github.com/modeset/teaspoon

**Comment by maurogeorge** [comment]
I think we can try the https://github.com/fnando/test_squad, I never used but we can create a sample app to test this.

**Comment by marano** [comment]
I've been using jasmine-rails [1] and my only complain is that it does not support test coverage. Besides that its great. I think test_squad would be pretty similar in functionality, I would be happy to try it.

For proper coverage support I am afraid we would need to use something like karma. I've used it with sinatra before, and it worked well because we were pointing to the raw js files. If we want to use something like babel, then its a different story because we would need to integrate with the asset pipeline. There is this rails_karma [2] gem which does just that, but I haven't tried it. Also, karma needs node installed.

[1] https://github.com/searls/jasmine-rails
[2] https://github.com/enspiral/rails_karma

**Comment by marano** [comment]
I failed to make clear that **I've mentioned karma because I think it is the proper choice**, I don't think coverage is something we can afford not having.

**Comment by lunks** [comment]
[rails_karma] has no tests and integrates with karma itself poorly AFAICT. :-1: 
Take a look at [teaspoon]. It supports [istanbul] for code coverage and has a bigger community than any of the other gems mentioned here so far.

[rails_karma]: https://github.com/enspiral/rails_karma
[teaspoon]: https://github.com/modeset/teaspoon
[istanbul]: https://github.com/gotwarlost/istanbul

**Comment by marano** [comment]
@lunks :100: looks awesome!

**Comment by marcioj** [comment]
:+1: for teaspoon.
